sudo: required
dist: trusty

language: php
php:
  - 5.6
node_js: "10"

env:
  - NOTE_RELEASE=8.x

cache:
  directories:
    - ~/.npm

before_install:
  - sudo rm -rf ~/.nvm - curl -sL "https://deb.nodesource.com/setup_${NODE_RELEASE}" | sudo -E bash -
  - sudo apt-get install -y nodejs

install:
  - npm install
  - cp ./typescript.d.ts ./node_modules/typescript/lib/typescript.d.ts
  - wget -O ./test/runtime/phpunit https://phar.phpunit.de/phpunit-5.phar

script:
  - npm test
  - npm run doc
  - npm run test:runtime

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep_history: true
  on:
    branch: master

deploy:
  provider: script
  skip_cleanup: true
  node_js: "10"
  install: npm ci
  script: npx semantic-release
  on:
    branch: master
